### ISSUE TITLE
Passing Buffer as input source

### ISSUE THREAD

**Issue by kingston** [mindee/mindee-api-nodejs#101]
Hi, I'm trying to use the Mindee API with our service. We're using pdf-lib to generate the PDF and then we need to upload it to Mindee. However, it generates the PDF as a Buffer object and currently it looks like I need to convert it to a hex encoding before I can upload it to Mindee via the API, which seems inefficient because it is then converting it back into a Buffer. Is it possible to create a new InputSource that allows passing a Buffer directly?

I actually prototyped a solution until I realized DocumentClient was a private class so I could not add this directly.

```
interface BufferInputProps {
  buffer: Buffer;
}

export class BufferInput extends InputSource {
  constructor({ buffer }: BufferInputProps) {
    super({
      inputType: INPUT_TYPE_BUFFER, // would need to be added as well
    });
    this.fileObject = buffer;
  }

  async init(): Promise<void> {
    this.mimeType = await this.checkMimetype();
  }
}
```

**Comment by ianardee** [comment]
Hi, thanks a lot for the suggestion and code snippet :smile: 

Just to understand your use case, if you have the data needed to generate the PDF, what data are you extracting using Mindee? 

We can discuss by email (look in the commit logs for Ianaré Sévi) if there are any confidential topics.

**Comment by kingston** [comment]
> Hi, thanks a lot for the suggestion and code snippet 😄
> 
> Just to understand your use case, if you have the data needed to generate the PDF, what data are you extracting using Mindee?
> 
> We can discuss by email (look in the commit logs for Ianaré Sévi) if there are any confidential topics.

Ah, I'm not creating a PDF from scratch. We're attempting to bulk extract from a PDF with multiple pages. Therefore, we need to divide the pages with pdf-lib and then upload each page individually to Mindee (it appears Mindee has a 5-page limit to the API).

This is also a scenario where we download a PDF from S3 as a Buffer and then want to upload it to Mindee. Right now, I was able to get it to work by hacking it on top of a ReadStream but it's nice to be able to work with Buffers since it's more memory efficient than base 64/hex.

**Comment by ianardee** [comment]
OK, understood.

So I'm thinking that it would be most helpful to be able to iterate over a multi-page document and send each page individually to the API, and then store the results at the page level in a standard `Document` object. Would you agree with this assessment?

We've actually had some users ask for this type of feature... but it's not the simplest thing to do in a generic fashion, given our other priorities.

In any case, I think adding a buffer input source is relatively painless and can have other uses, as you say.

Right now I'm doing some work on the Python client, but can probably have something for you next week.

**Comment by ianardee** [comment]
BTW, regarding the page limit, in some cases we can increase it, feel free to contact me over email or on intercom (the bright red bubble at the bottom left of [mindee.com](https://mindee.com/):

![Screenshot_20221103_172606](https://user-images.githubusercontent.com/97107275/199777637-bc1b5849-29fb-46ea-a4e3-86c300416c51.png)

**Comment by ianardee** [comment]
This functionality was added in version 3.1.1, now available on NPM.
