### ISSUE TITLE
Not able to import module

### ISSUE THREAD

**Issue by junedlanja** [mindee/mindee-api-nodejs#130]
### Description

Not able to import the module
<img width="915" alt="Screenshot 2022-12-08 at 23 25 02" src="https://user-images.githubusercontent.com/11869570/206528187-062a2765-1dd1-4f43-b521-132bfe6c8b2a.png">

### Steps to Reproduce
1. Installed the latest version
2. Try to import the module on an express server

**Expected behavior:**
I should be able to import the module & use it

**Actual behavior:**
Getting this error attached below

**Reproduces how often:**
Every time

### Versions
3.3.0

**Comment by junedlanja** [comment]
You can download this sample code from your demo repo
[[demo-Nodejs-SDK](https://github.com/mindee/demo-Nodejs-SDK)](https://github.com/mindee/demo-Nodejs-SDK)

Just change **mindee** version from 1.0.9 to latest one

**Comment by ianardee** [comment]
Which version of node.js are you using?
