### ISSUE TITLE
Some types are not exported in the top-level index.ts

### ISSUE THREAD

**Issue by potb** [mindee/mindee-api-nodejs#247]
### Prerequisites

* [X] Reproduced the problem or exposed a new need
* [X] Checked the github existing issues

### Description

Consuming some unexported types from the SDK can be tricky :
- the `Inference` type is only accessible by importing `mindee/src/parsing/common`
- the `CustomV1` type is only accessible by importing `mindee/src/product`

### Steps to Reproduce

- import `Inference` or `CustomV1`

**Expected behavior:**

Use the top-level export `mindee` instead of a fully qualified one.

**Actual behavior:**

Use a fully qualified one `mindee/src/parsing/common` or `mindee/src/product`

**Reproduces how often:**

It happens when we want to strongly type our functions, based on what the sdk provides us with.
In our case, we use `AsyncPredictResponse` and want to type it using `Inference<MindeePrediction>`

### Versions

- Node 16.20.2
- mindee 4.6.1

**Comment by potb** [comment]
Great, thank you for your feedback !

**Comment by sebastianMindee** [comment]
Addressed in #251 

In summary: Inference will get bumped to top-level export for ease of access, products remain in their namespaces. Other internals will stay in their namespaces but the discussion for fields might be re-opened at a later date.

**Comment by potb** [comment]
Alright, thank you for the follow-up !
