### ISSUE TITLE
Misleading onMinPages options when cutting PDF before predicting

### ISSUE THREAD

**Issue by PaulinL** [mindee/mindee-api-nodejs#296]
### Prerequisites

* [x] Reproduced the problem or exposed a new need
* [x] Checked the github existing issues

### Description

When requesting a prediction, `pageOptions` allows to specify a `onMinPages` parameter to remove pages from a document only if the number of pages is above the value. However, when the file has less pages that the `onMinPages` value and `pageIndexes` has more indexes than `onMinPages`, we get the following error : 
```
The total indexes of pages to cut is superior to the total page count of the file (3)
```

### Steps to Reproduce

1. Use the following `pageOptions` :
```ts
pageOptions: {
  operation: PageOptionsOperation.KeepOnly,
  pageIndexes: [0, 1, 2, -1, -2, -3],
  onMinPages: 10,
}
```
2. Request a prediction for a PDF that has less than 6 pages

**Expected behavior:**

It should not cut the document, not throw an error and send the request. 

**Actual behavior:**

We get the following error :
```
The total indexes of pages to cut is superior to the total page count of the file (3)
```

**Reproduces how often:**

100%

### Versions

Version 4.14.1 

### Additional Information

I guess the solution would simply to invert the conditions in the [extractPages](https://github.com/mindee/mindee-api-nodejs/blob/4ab6bf5b0699bf22b47bfa9e5ec46671d1416a90/src/pdf/pdfOperation.ts#L17) method so we directly return the file if the number of pages is below `onMinPages`. I can open a pull request if needed.

**Comment by sebastianMindee** [comment]
Fixed in #297
