### ISSUE TITLE
cutPdf parameter has no effect when passing inputs of type stream

### ISSUE THREAD

**Issue by jonathanMindee** [mindee/mindee-api-nodejs#46]
### Prerequisites

Put an X between the brackets on this line if you have done all of the following:

* [x] Reproduced the problem or exposed a new need
* [x] Checked the github existing issues

### Description

The cutPdf parameter has no effect when using the "stream" input type support. I tested with a 12 pages documents and got an error "Maximum pdf pages is 10". I tested with the same document using the "path" input type and it's working.

### Steps to Reproduce

1. Download this file: 
[12pages.pdf](https://github.com/mindee/mindee-api-nodejs/files/7602228/12pages.pdf)

2. Execute this code
```javascript
const { Client } = require("mindee");
const fs = require("fs");

const mindeeClient = new Client({invoiceToken: "yourTokenHere"});

const stream = fs.createReadStream("./12pages.pdf");
mindeeClient.invoice
    .parse({ input: stream, inputType: "stream", cutPdf: true })
    .then((res) => {
        console.log("Success !");
        console.log(res.invoice);
    })
    .catch((err) => {
        console.error(err);
    });
```
3. An HTTP error will be thrown

**Expected behavior:**

The cutPdf parameter should work on all input type (path, stream, and base64)

**Comment by fharper** [comment]
Fixed in v.1.0.7
